# -*- coding: utf-8 -*-
"""Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lxENRmUqhn7Es_Cq4YI8um26n3l2Xz-k
"""

#Create a dictionary

finalData=[]
employeeId=0
while(1):
 print("Press 1 to enter the employee details")
 print("Enter 2 to quit")

 i=int(input())

 if i==1 :
  employeeData={}
  employeeId+=1
  
  
  employeeData["employeeId"]=employeeId
  
  str1=input("Enter employee name")
  employeeData["employeeName"]=str1

  str2=input("Enter employee age")
  employeeData["employeeAge"]=str2


  str3=input("Enter employee gender")
  employeeData["employeeGenger"]=str3

  str4=input("Enter employee phoneno")
  employeeData["employeePhoneno"]=str4

  str5=input("Enter employee location")
  employeeData["employeeLocation"]=str5

  str6=input("Enter employee department")
  employeeData["employeeDept"]=str6

  str7=input("Enter employee salary")
  employeeData["employeeSalary"]=str7

  finalData.append(employeeData)


 

  

  
 elif i==2 :
  print(finalData)
  break;

#Create blockchain
import hashlib
class neuralCoinBlock:
  def __init__(self,preBlockHash,tranList):
    self.preBlockHash=preBlockHash
    self.tranList=tranList


    self.blockData="-".join(tranList)+"-"+preBlockHash
    self.blockHash=hashlib.sha256(self.blockData.encode()).hexdigest()

InitialBlock=neuralCoinBlock("Encode Password", "ewewew")

InitialBlock.blockData

InitialBlock.blockHash

values = ','.join(str(v) for v in finalData)


SecondBlock=neuralCoinBlock(InitialBlock.blockHash, values)
SecondBlock.blockHash

#Adding timestamp

index=[]
import datetime
import pytz
def createBlock(prevHash,data):
  b=neuralCoinBlock(prevHash,data)
  index.append([b.blockHash,datetime.datetime.now(pytz.timezone('Asia/Kolkata'))])
  return b.blockHash

createBlock("0fc23d7073283cb9dd76670c2f797b34a891e4e55e6f2607f694fd10a12811fd",values)
print(index)